---
platform: linux

image_resource:
  type: docker-image
  source:
   repository: ubuntu
   tag: latest

inputs:
- name: resource-grpc-calculator

run:
  path: resource-grpc-calculator/grpc_calculator/calculator/make

