---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
- name: resource-grpc-calculator

run:
  path: resource-grpc-calculator/grpc_calculator_calculator/make

