---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: openjdk
    tag: 8

inputs:
 - name: resource-spring-mvc-webapp    

run:
  path: resource-spring-mvc-webapp/build.sh
