---
# YAML config file to deploy all projects using concourse
groups:
  - name: web-apps
    jobs:
      - deploy-spring-mvc-webapp
      - deploy-spring-security-webapp

  - name: grpc-based-apps
    jobs:
      - deploy-grpc-calculator

resources:
- name: resource-deployment-repo
  type: git
  source:
    uri: https://github.com/PrateekJoshi/concourse
    branch: master

- name: resource-spring-mvc-webapp
  type: git
  source:
    uri: https://github.com/PrateekJoshi/spring-mvc-app
    branch: master


jobs:
  - name: deploy-spring-mvc-webapp
    serial: true
    plan:
      - get: resource-spring-mvc-webapp
      - get: resource-deployment-repo
      - task: run-spring-mvc-webapp
        file: resource-deployment-repo/tasks/run-spring-mvc-webapp.yml




  - name: deploy-spring-security-webapp

  - name: deploy-grpc-calculator
